[package]
name = "dispenser"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
camino = "1"
petname = "1"
thrussh = "0.32"
thrussh-keys = "0.20"
futures-util = "0.3"
pretty_env_logger = "0.4"
tokio-cron-scheduler = "0.2"