[package]
name = "dispenser"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
camino = "1"
petname = "1"
thrussh = "0.33"
thrussh-keys = "0.21"
futures-util = "0.3"
pretty_env_logger = "0.4"
cron = "0.11.0"
rcon = { version = "0.6.0", features = ["rt-tokio"] }
tracing = "0.1.33"
tracing-subscriber = "0.3.11"
clap = { version = "3.1.8", features = ["derive"] }
main_error = "0.1.2"