name: Release

on:
  release:
    types: [created]


jobs:
  release-binaries:
    name: Build release binaries
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/dispenser
          asset_name: dispenser
          tag: ${{ github.ref }}
